# Generated by Django 5.0.3 on 2025-04-11 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(verbose_name='目标URL')),
                ('scan_type', models.CharField(max_length=50, verbose_name='扫描类型')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '扫描中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '扫描任务',
                'verbose_name_plural': '扫描任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnerability_type', models.CharField(max_length=50, verbose_name='漏洞类型')),
                ('severity', models.CharField(choices=[('high', '高危'), ('medium', '中危'), ('low', '低危'), ('info', '信息')], max_length=20, verbose_name='严重程度')),
                ('description', models.TextField(verbose_name='漏洞描述')),
                ('affected_url', models.URLField(verbose_name='受影响URL')),
                ('details', models.JSONField(verbose_name='详细信息')),
                ('discovered_at', models.DateTimeField(auto_now_add=True, verbose_name='发现时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scan.scantask', verbose_name='扫描任务')),
            ],
            options={
                'verbose_name': '扫描结果',
                'verbose_name_plural': '扫描结果',
                'ordering': ['-discovered_at'],
            },
        ),
    ]
