# Generated by Django 5.0.3 on 2025-04-08 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='目标URL')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '扫描目标',
                'verbose_name_plural': '扫描目标',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('port', '端口扫描'), ('os', '操作系统扫描'), ('sql', 'SQL注入扫描'), ('xss', 'XSS扫描'), ('dir', '目录扫描'), ('info', '信息泄露扫描')], max_length=10, verbose_name='扫描类型')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '扫描中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vulnscan.target', verbose_name='扫描目标')),
            ],
            options={
                'verbose_name': '扫描任务',
                'verbose_name_plural': '扫描任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='漏洞标题')),
                ('description', models.TextField(verbose_name='漏洞描述')),
                ('severity', models.CharField(choices=[('low', '低危'), ('medium', '中危'), ('high', '高危'), ('critical', '严重')], max_length=10, verbose_name='危险等级')),
                ('solution', models.TextField(blank=True, verbose_name='修复建议')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发现时间')),
                ('scan_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vulnscan.scantask', verbose_name='扫描任务')),
            ],
            options={
                'verbose_name': '漏洞信息',
                'verbose_name_plural': '漏洞信息',
                'ordering': ['-created_at'],
            },
        ),
    ]
